# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.26

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /class/classes/lguzm044/final-project-lguzm044_schav088_tadel002_habdu016

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /class/classes/lguzm044/final-project-lguzm044_schav088_tadel002_habdu016

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"gmock\" \"gtest\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /class/classes/lguzm044/final-project-lguzm044_schav088_tadel002_habdu016/CMakeFiles /class/classes/lguzm044/final-project-lguzm044_schav088_tadel002_habdu016//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /class/classes/lguzm044/final-project-lguzm044_schav088_tadel002_habdu016/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named start_game

# Build rule for target.
start_game: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 start_game
.PHONY : start_game

# fast build rule for target.
start_game/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/start_game.dir/build.make CMakeFiles/start_game.dir/build
.PHONY : start_game/fast

#=============================================================================
# Target rules for targets named character_test

# Build rule for target.
character_test: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 character_test
.PHONY : character_test

# fast build rule for target.
character_test/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/character_test.dir/build.make CMakeFiles/character_test.dir/build
.PHONY : character_test/fast

#=============================================================================
# Target rules for targets named gmock

# Build rule for target.
gmock: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gmock
.PHONY : gmock

# fast build rule for target.
gmock/fast:
	$(MAKE) $(MAKESILENT) -f googletest/googlemock/CMakeFiles/gmock.dir/build.make googletest/googlemock/CMakeFiles/gmock.dir/build
.PHONY : gmock/fast

#=============================================================================
# Target rules for targets named gmock_main

# Build rule for target.
gmock_main: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gmock_main
.PHONY : gmock_main

# fast build rule for target.
gmock_main/fast:
	$(MAKE) $(MAKESILENT) -f googletest/googlemock/CMakeFiles/gmock_main.dir/build.make googletest/googlemock/CMakeFiles/gmock_main.dir/build
.PHONY : gmock_main/fast

#=============================================================================
# Target rules for targets named gtest

# Build rule for target.
gtest: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gtest
.PHONY : gtest

# fast build rule for target.
gtest/fast:
	$(MAKE) $(MAKESILENT) -f googletest/googletest/CMakeFiles/gtest.dir/build.make googletest/googletest/CMakeFiles/gtest.dir/build
.PHONY : gtest/fast

#=============================================================================
# Target rules for targets named gtest_main

# Build rule for target.
gtest_main: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gtest_main
.PHONY : gtest_main

# fast build rule for target.
gtest_main/fast:
	$(MAKE) $(MAKESILENT) -f googletest/googletest/CMakeFiles/gtest_main.dir/build.make googletest/googletest/CMakeFiles/gtest_main.dir/build
.PHONY : gtest_main/fast

src/character.o: src/character.cpp.o
.PHONY : src/character.o

# target to build an object file
src/character.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/start_game.dir/build.make CMakeFiles/start_game.dir/src/character.cpp.o
.PHONY : src/character.cpp.o

src/character.i: src/character.cpp.i
.PHONY : src/character.i

# target to preprocess a source file
src/character.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/start_game.dir/build.make CMakeFiles/start_game.dir/src/character.cpp.i
.PHONY : src/character.cpp.i

src/character.s: src/character.cpp.s
.PHONY : src/character.s

# target to generate assembly for a file
src/character.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/start_game.dir/build.make CMakeFiles/start_game.dir/src/character.cpp.s
.PHONY : src/character.cpp.s

src/dragonborn.o: src/dragonborn.cpp.o
.PHONY : src/dragonborn.o

# target to build an object file
src/dragonborn.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/start_game.dir/build.make CMakeFiles/start_game.dir/src/dragonborn.cpp.o
.PHONY : src/dragonborn.cpp.o

src/dragonborn.i: src/dragonborn.cpp.i
.PHONY : src/dragonborn.i

# target to preprocess a source file
src/dragonborn.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/start_game.dir/build.make CMakeFiles/start_game.dir/src/dragonborn.cpp.i
.PHONY : src/dragonborn.cpp.i

src/dragonborn.s: src/dragonborn.cpp.s
.PHONY : src/dragonborn.s

# target to generate assembly for a file
src/dragonborn.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/start_game.dir/build.make CMakeFiles/start_game.dir/src/dragonborn.cpp.s
.PHONY : src/dragonborn.cpp.s

src/dwarf.o: src/dwarf.cpp.o
.PHONY : src/dwarf.o

# target to build an object file
src/dwarf.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/start_game.dir/build.make CMakeFiles/start_game.dir/src/dwarf.cpp.o
.PHONY : src/dwarf.cpp.o

src/dwarf.i: src/dwarf.cpp.i
.PHONY : src/dwarf.i

# target to preprocess a source file
src/dwarf.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/start_game.dir/build.make CMakeFiles/start_game.dir/src/dwarf.cpp.i
.PHONY : src/dwarf.cpp.i

src/dwarf.s: src/dwarf.cpp.s
.PHONY : src/dwarf.s

# target to generate assembly for a file
src/dwarf.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/start_game.dir/build.make CMakeFiles/start_game.dir/src/dwarf.cpp.s
.PHONY : src/dwarf.cpp.s

src/elf.o: src/elf.cpp.o
.PHONY : src/elf.o

# target to build an object file
src/elf.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/start_game.dir/build.make CMakeFiles/start_game.dir/src/elf.cpp.o
.PHONY : src/elf.cpp.o

src/elf.i: src/elf.cpp.i
.PHONY : src/elf.i

# target to preprocess a source file
src/elf.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/start_game.dir/build.make CMakeFiles/start_game.dir/src/elf.cpp.i
.PHONY : src/elf.cpp.i

src/elf.s: src/elf.cpp.s
.PHONY : src/elf.s

# target to generate assembly for a file
src/elf.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/start_game.dir/build.make CMakeFiles/start_game.dir/src/elf.cpp.s
.PHONY : src/elf.cpp.s

src/enemy.o: src/enemy.cpp.o
.PHONY : src/enemy.o

# target to build an object file
src/enemy.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/start_game.dir/build.make CMakeFiles/start_game.dir/src/enemy.cpp.o
.PHONY : src/enemy.cpp.o

src/enemy.i: src/enemy.cpp.i
.PHONY : src/enemy.i

# target to preprocess a source file
src/enemy.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/start_game.dir/build.make CMakeFiles/start_game.dir/src/enemy.cpp.i
.PHONY : src/enemy.cpp.i

src/enemy.s: src/enemy.cpp.s
.PHONY : src/enemy.s

# target to generate assembly for a file
src/enemy.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/start_game.dir/build.make CMakeFiles/start_game.dir/src/enemy.cpp.s
.PHONY : src/enemy.cpp.s

src/human.o: src/human.cpp.o
.PHONY : src/human.o

# target to build an object file
src/human.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/start_game.dir/build.make CMakeFiles/start_game.dir/src/human.cpp.o
.PHONY : src/human.cpp.o

src/human.i: src/human.cpp.i
.PHONY : src/human.i

# target to preprocess a source file
src/human.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/start_game.dir/build.make CMakeFiles/start_game.dir/src/human.cpp.i
.PHONY : src/human.cpp.i

src/human.s: src/human.cpp.s
.PHONY : src/human.s

# target to generate assembly for a file
src/human.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/start_game.dir/build.make CMakeFiles/start_game.dir/src/human.cpp.s
.PHONY : src/human.cpp.s

src/interaction.o: src/interaction.cpp.o
.PHONY : src/interaction.o

# target to build an object file
src/interaction.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/start_game.dir/build.make CMakeFiles/start_game.dir/src/interaction.cpp.o
.PHONY : src/interaction.cpp.o

src/interaction.i: src/interaction.cpp.i
.PHONY : src/interaction.i

# target to preprocess a source file
src/interaction.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/start_game.dir/build.make CMakeFiles/start_game.dir/src/interaction.cpp.i
.PHONY : src/interaction.cpp.i

src/interaction.s: src/interaction.cpp.s
.PHONY : src/interaction.s

# target to generate assembly for a file
src/interaction.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/start_game.dir/build.make CMakeFiles/start_game.dir/src/interaction.cpp.s
.PHONY : src/interaction.cpp.s

src/main.o: src/main.cpp.o
.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/start_game.dir/build.make CMakeFiles/start_game.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/start_game.dir/build.make CMakeFiles/start_game.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/start_game.dir/build.make CMakeFiles/start_game.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

test/charactertest.o: test/charactertest.cpp.o
.PHONY : test/charactertest.o

# target to build an object file
test/charactertest.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/character_test.dir/build.make CMakeFiles/character_test.dir/test/charactertest.cpp.o
.PHONY : test/charactertest.cpp.o

test/charactertest.i: test/charactertest.cpp.i
.PHONY : test/charactertest.i

# target to preprocess a source file
test/charactertest.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/character_test.dir/build.make CMakeFiles/character_test.dir/test/charactertest.cpp.i
.PHONY : test/charactertest.cpp.i

test/charactertest.s: test/charactertest.cpp.s
.PHONY : test/charactertest.s

# target to generate assembly for a file
test/charactertest.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/character_test.dir/build.make CMakeFiles/character_test.dir/test/charactertest.cpp.s
.PHONY : test/charactertest.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... character_test"
	@echo "... gmock"
	@echo "... gmock_main"
	@echo "... gtest"
	@echo "... gtest_main"
	@echo "... start_game"
	@echo "... src/character.o"
	@echo "... src/character.i"
	@echo "... src/character.s"
	@echo "... src/dragonborn.o"
	@echo "... src/dragonborn.i"
	@echo "... src/dragonborn.s"
	@echo "... src/dwarf.o"
	@echo "... src/dwarf.i"
	@echo "... src/dwarf.s"
	@echo "... src/elf.o"
	@echo "... src/elf.i"
	@echo "... src/elf.s"
	@echo "... src/enemy.o"
	@echo "... src/enemy.i"
	@echo "... src/enemy.s"
	@echo "... src/human.o"
	@echo "... src/human.i"
	@echo "... src/human.s"
	@echo "... src/interaction.o"
	@echo "... src/interaction.i"
	@echo "... src/interaction.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... test/charactertest.o"
	@echo "... test/charactertest.i"
	@echo "... test/charactertest.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system